language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.ValueObject.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.ValueObject.sln
  - dotnet restore
  - dotnet test ValueObject.Test/ValueObject.Test.csproj
